### ISSUE TITLE
Add more events statuses and refactor existing enums

### ISSUE THREAD

**Issue by raczu** [wzarek/Reasn#52]
### What new thing should be implemented?

The aim is to add a status that will inform that the event has been canceled and one more with information about its rejection by administrator. The rest of the exisitng statuses should be refactored to try to describe its condition in a single word.

### What is your acceptance criteria?

As described above.

**Comment by wzarek** [comment]
Why in a single word? Can't we just leave as it is and when creating enums on FE side just format them properly and hardcode the info about it to display it as a tooltip when you hover or click info icon for example? But cancelled yeah, agree that it should be added
